#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

echo "Running tests..."
npm run test:ci || {
  echo "Tests failed! Commit bypassed."
  exit 1
}

echo "Running linter and typescript checks..."
npx lint-staged
npx tsc --noEmit
